# 服务器配置
server:
  port: 9999

spring:
  # 数据库配置
  datasource:
#    driver-class-name: org.gjt.mm.mysql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis_cache_test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1

# mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: net.khcloud.study.dao.domain
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: classpath:mappers/**/*.xml
#    - mappers/ProductMapper.xml

standby:
  # 数据库配置
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/redis_cache_test_bak?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

#    # mongodb
#    # demo:  https://github.com/mongodb/mongo-jdbc-driver/blob/master/demo/src/main/java/com/mongodb/jdbc/demo/Main.java
#    driver-class-name:  com.mongodb.jdbc.MongoDriver
#    type: com.zaxxer.hikari.HikariDataSource
##    url: jdbc:mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?option1=value1[&option2=value2]...]
#    url: jdbc:mongodb://127.0.0.1:27017/redis_cache_test
#    username: admin
#    password: 123456

logging:
  level:
    com.ccb.ftech: DEBUG

---
spring:
  profiles: test
  # 数据库配置
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql